### ISSUE TITLE
Apply pull request 6, key handling is still a problem

### ISSUE THREAD

**Issue by stuaxo** [nodebox/nodebox-opengl#11]
I had to apply a similar fix at the beginning of a live event using nodebox the other day, please apply the patch.

https://github.com/nodebox/nodebox-opengl/pull/6

FWIW - the bug manifests in gnome-shell, which is pretty popular.

**Comment by fdb** [comment]
Done.

**Comment by stuaxo** [comment]
Thanks, tested that works :)

Any change of applying the one I linked to in here  https://github.com/nodebox/nodebox-opengl/issues/10 as well ?
